<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Xu Qianqian">
<meta name="dcterms.date" content="2026-03-06">

<title>Take-home Exercise 2 – ISSS608-Visual Analytics and Applications</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-a4b0e55808e3ccc7f2d55f5de6650844.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> <i class="bi bi-house-fill" role="img">
</i> 
<span class="menu-text">ISSS608-Visual Analytics &amp; Applications</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html">
 <span class="dropdown-text">Hands-on Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html">
 <span class="dropdown-text">Hands-on Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03a.html">
 <span class="dropdown-text">Hands-on Exercise 3a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03b.html">
 <span class="dropdown-text">Hands-on Exercise 3b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04a.html">
 <span class="dropdown-text">Hands-on Exercise 4a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04b.html">
 <span class="dropdown-text">Hands-on Exercise 4b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04c.html">
 <span class="dropdown-text">Hands-on Exercise 4c</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04d.html">
 <span class="dropdown-text">Hands-on Exercise 4d</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05a.html">
 <span class="dropdown-text">Hands-on Exercise 5a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05b.html">
 <span class="dropdown-text">Hands-on Exercise 5b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05c.html">
 <span class="dropdown-text">Hands-on Exercise 5c</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05d.html">
 <span class="dropdown-text">Hands-on Exercise 5d</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05e.html">
 <span class="dropdown-text">Hands-on Exercise 5e</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html">
 <span class="dropdown-text">Hands-on Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07a.html">
 <span class="dropdown-text">Hands-on Exercise 7a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07b.html">
 <span class="dropdown-text">Hands-on Exercise 7b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07c.html">
 <span class="dropdown-text">Hands-on Exercise 7c</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html">
 <span class="dropdown-text">Hands-on Exercise 8</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html">
 <span class="dropdown-text">Take-home Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html">
 <span class="dropdown-text">Take-home Exercise 2</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/keaidewoq"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/xuqianqian0706"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#predictive-modelling" id="toc-predictive-modelling" class="nav-link active" data-scroll-target="#predictive-modelling">Predictive Modelling</a>
  <ul class="collapse">
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">1 Overview</a></li>
  <li><a href="#install-and-load-packages" id="toc-install-and-load-packages" class="nav-link" data-scroll-target="#install-and-load-packages">2 Install and Load Packages</a></li>
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">3 Data Preparation</a>
  <ul class="collapse">
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">3.1 The Data</a></li>
  <li><a href="#import-data" id="toc-import-data" class="nav-link" data-scroll-target="#import-data">3.2 Import Data</a></li>
  <li><a href="#preparing-the-data" id="toc-preparing-the-data" class="nav-link" data-scroll-target="#preparing-the-data">3.3 Preparing the Data</a></li>
  </ul></li>
  <li><a href="#analytical-workflow" id="toc-analytical-workflow" class="nav-link" data-scroll-target="#analytical-workflow">4 Analytical Workflow</a>
  <ul class="collapse">
  <li><a href="#feature-engineering-and-variable-selection" id="toc-feature-engineering-and-variable-selection" class="nav-link" data-scroll-target="#feature-engineering-and-variable-selection">4.1 Feature Engineering and Variable Selection</a></li>
  <li><a href="#univariate-distribution-analysis" id="toc-univariate-distribution-analysis" class="nav-link" data-scroll-target="#univariate-distribution-analysis">4.2 Univariate distribution Analysis</a></li>
  <li><a href="#correlation-matrix" id="toc-correlation-matrix" class="nav-link" data-scroll-target="#correlation-matrix">4.3 Correlation Matrix</a></li>
  <li><a href="#stratified-random-sampling" id="toc-stratified-random-sampling" class="nav-link" data-scroll-target="#stratified-random-sampling">4.4 Stratified Random Sampling</a></li>
  <li><a href="#variance-inflation-factor-vif" id="toc-variance-inflation-factor-vif" class="nav-link" data-scroll-target="#variance-inflation-factor-vif">4.5 Variance Inflation Factor (VIF)</a></li>
  </ul></li>
  <li><a href="#building-predictive-models" id="toc-building-predictive-models" class="nav-link" data-scroll-target="#building-predictive-models">5 Building Predictive Models</a>
  <ul class="collapse">
  <li><a href="#create-the-preprocessing-recipe" id="toc-create-the-preprocessing-recipe" class="nav-link" data-scroll-target="#create-the-preprocessing-recipe">5.1 Create the Preprocessing Recipe</a></li>
  <li><a href="#tune-and-fit-the-models" id="toc-tune-and-fit-the-models" class="nav-link" data-scroll-target="#tune-and-fit-the-models">5.2 Tune and Fit the Models</a></li>
  <li><a href="#model-performance-and-comparison" id="toc-model-performance-and-comparison" class="nav-link" data-scroll-target="#model-performance-and-comparison">5.3 Model Performance and Comparison</a></li>
  <li><a href="#variable-importance-random-forest" id="toc-variable-importance-random-forest" class="nav-link" data-scroll-target="#variable-importance-random-forest">5.4 Variable Importance (Random Forest)</a></li>
  <li><a href="#business-takeaway" id="toc-business-takeaway" class="nav-link" data-scroll-target="#business-takeaway">5.5 Business Takeaway</a></li>
  </ul></li>
  <li><a href="#ui-design" id="toc-ui-design" class="nav-link" data-scroll-target="#ui-design">6 UI Design</a>
  <ul class="collapse">
  <li><a href="#tab-1-macro-view-strategic-oversight" id="toc-tab-1-macro-view-strategic-oversight" class="nav-link" data-scroll-target="#tab-1-macro-view-strategic-oversight">Tab 1: Macro View (Strategic Oversight)</a></li>
  <li><a href="#tab-2-micro-view-operational-simulation" id="toc-tab-2-micro-view-operational-simulation" class="nav-link" data-scroll-target="#tab-2-micro-view-operational-simulation">Tab 2: Micro View (Operational Simulation)</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home Exercise 2</h1>
</div>



<div class="quarto-title-meta column-page-left">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Xu Qianqian </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 6, 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">March 14, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="predictive-modelling" class="level1">
<h1>Predictive Modelling</h1>
<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">1 Overview</h2>
<p>This project aims to develop a robust predictive model to identify customer churn within a Colombian fintech environment. Using the <strong>COFINFAD</strong> dataset, which tracks the behavior of 48,723 customers over the 2023 calendar year, the analysis bridges the gap between customer sentiment and actual transactional behavior. By converting over 3.1 million raw transaction logs into actionable behavioral metrics, the project provides a data-driven strategy for proactive customer retention.</p>
</section>
<section id="install-and-load-packages" class="level2">
<h2 class="anchored" data-anchor-id="install-and-load-packages">2 Install and Load Packages</h2>
<p>In this project, we utilize eighteen R packages to facilitate data import, manipulation, and advanced visualization:</p>
<ul>
<li><p><strong><code>tidyverse</code></strong>: A collection of fundamental R packages designed for data science, covering everything from data cleaning to creating static statistical graphs.</p></li>
<li><p><strong><code>naniar</code></strong>: Provides a suite of functions to tidy, visualize, and analyze <strong>missing data</strong> (NAs)</p></li>
<li><p><strong><code>skimr</code></strong>: A tool for <strong>quick data assessment</strong>. It produces a “skim” of a dataframe, providing summary statistics (mean, SD, quantiles) and tiny inline histograms (sparklines) for a fast overview of distributions.</p></li>
<li><p><strong><code>knitr</code></strong>: The engine behind <strong>dynamic report generation</strong> in R. It integrates R code into Markdown, LaTeX, or HTML documents, allowing you to “knit” your analysis into a finished report.</p></li>
<li><p><strong><code>dplyr</code></strong>: It’s the package for <strong>filtering, selecting, mutating, and summarizing</strong> dataframes using a clean, readable syntax.</p></li>
<li><p><strong><code>kableExtra</code></strong>: An extension for <code>knitr::kable()</code> that provides advanced styling options for <strong>HTML and PDF tables</strong>, such as striped rows, hover effects, and complex headers.</p></li>
<li><p><strong><code>patchwork</code></strong>: Makes <strong>combining multiple ggplots</strong> incredibly simple.</p></li>
<li><p><strong><code>corrplot</code></strong>: A graphical display of a <strong>correlation matrix</strong>. It helps you quickly identify patterns and strengths of relationships between variables using colors and shapes.</p></li>
<li><p><strong><code>tidymodels</code></strong>: A “meta-package” (like the tidyverse) designed for <strong>modeling and machine learning</strong>. It provides a consistent framework for preprocessing, training, and validating models.</p></li>
<li><p><strong><code>ranger</code></strong>: A fast implementation of <strong>Random Forests</strong>. It is highly memory-efficient and particularly well-suited for high-dimensional data.</p></li>
<li><p><strong><code>xgboost</code></strong>: An interface for <strong>Extreme Gradient Boosting</strong>. It’s a powerful, scalable library used for gradient-boosted decision trees, often favored in data science competitions for its speed and performance.</p></li>
<li><p><strong><code>vip</code></strong>: Stands for <strong>Variable Importance Plots</strong>. It extracts and visualizes the importance of features in various machine learning models, helping you understand which variables are driving your model’s predictions.</p></li>
<li><p><strong><code>car</code></strong>: provides advanced statistical tests and diagnostic tools—such as the <code>vif()</code> function—to evaluate, troubleshoot, and refine regression models.</p></li>
<li><p><strong><code>rsample</code></strong>: provides the tools to split your data into training and testing sets, as well as create resampled data like cross-validation folds.</p></li>
<li><p><strong><code>tune</code></strong>: helps optimize your machine learning models by testing and finding the best possible hyperparameter values.</p></li>
<li><p><strong><code>parsnip</code></strong>: gives a single, standardized interface to build and fit various types of machine learning models</p></li>
<li><p><strong><code>workflows</code></strong>: simplifies your coding pipeline by bundling your data pre-processing steps and the <code>parsnip</code> model into one cohesive object that can be trained and tested together.</p></li>
<li><p><strong><code>yardstick</code></strong>: provides a consistent, tidy interface for calculating model performance metrics</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse, naniar, skimr, knitr, dplyr,kableExtra, patchwork, corrplot, tidymodels,ranger, xgboost,vip,car, rsample, tune, parsnip, workflows, yardstick)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="data-preparation" class="level2">
<h2 class="anchored" data-anchor-id="data-preparation">3 Data Preparation</h2>
<section id="the-data" class="level3">
<h3 class="anchored" data-anchor-id="the-data">3.1 The Data</h3>
<p>This project analyzes the <a href="https://data.mendeley.com/datasets/mhb4zn3258/1">Colombian Fintech Financial Analytics Dataset</a> (COFINFAD). The dataset contains behavioral and transactional records for 48,723 customers, collected over a 12-month period from January 4 to December 29, 2023. Comprising over 3.1 million individual transactions, the data is designed to support research on customer retention, financial behavior, and digital service adoption in emerging Latin American markets.</p>
<p>The dataset consists of two CSV files:</p>
<ul>
<li><p><strong><code>transactions_data.csv</code></strong>: Transaction-level data (3,159,157 rows), where each row represents a single transaction.</p></li>
<li><p><strong><code>customer_data.csv</code></strong>: Customer-level data (48,723 rows), including demographics, product portfolios, satisfaction metrics, and aggregated behavioral features.</p></li>
</ul>
</section>
<section id="import-data" class="level3">
<h3 class="anchored" data-anchor-id="import-data">3.2 Import Data</h3>
<p>The following code chunk utilizes the <strong><code>read_csv()</code></strong> function from the <strong><code>readr</code></strong> package (part of the <strong>tidyverse</strong>) to import the datasets into the R environment.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>customer_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/customer_data.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>transactions_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/transactions_data.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="preparing-the-data" class="level3">
<h3 class="anchored" data-anchor-id="preparing-the-data">3.3 Preparing the Data</h3>
<section id="check-missing-values" class="level4">
<h4 class="anchored" data-anchor-id="check-missing-values">3.3.1 Check Missing Values</h4>
<p>I use <code>gg_miss_var(customer_data)</code> to get an instant, clear picture of <strong>which columns in the dataset are missing the most information</strong>. Instead of scrolling through a massive table of <code>NA</code> counts, this function (from the <code>naniar</code> package) generates a simple bar chart.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Plot</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Code</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize missingness in customer data</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gg_miss_var</span>(customer_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
<p>In the customer dataset (<span class="math inline">\(N = 48,723\)</span>), missing values are limited to <code>complaint_topics</code> (49.97%), <code>credit_utilization_ratio</code> (37.48%), and <code>feature_requests</code> (33.07%). These gaps are structural, occurring when a product or interaction is not applicable to the customer. Categorical missing values were imputed as ‘None’ or ‘No Interaction’. For <code>credit_utilization_ratio</code>, NAs were filled with 0.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>customer_data_clean <span class="ot">&lt;-</span> customer_data <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># 1. Impute numerical data with 0 </span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">credit_utilization_ratio =</span> <span class="fu">replace_na</span>(credit_utilization_ratio, <span class="dv">0</span>),</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># 2. Impute categorical data with 'None' and 'No Interaction'</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">complaint_topics =</span> <span class="fu">replace_na</span>(complaint_topics, <span class="st">"None"</span>),</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">feature_requests =</span> <span class="fu">replace_na</span>(feature_requests, <span class="st">"No Interaction"</span>),</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize missingness in transaction data</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gg_miss_var</span>(transactions_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>All transaction-level variables are complete.</p>
</section>
<section id="data-wrangling" class="level4">
<h4 class="anchored" data-anchor-id="data-wrangling">3.3.2 Data Wrangling</h4>
<section id="recency-frequency-and-monetary" class="level5">
<h5 class="anchored" data-anchor-id="recency-frequency-and-monetary">3.3.2.1 Recency, Frequency, and Monetary</h5>
<p>To enhance the predictive power of the model, I will perform feature engineering on the <code>transactions_data.csv</code> to derive the <strong>RFM</strong> (Recency, Frequency, and Monetary) metrics for each of the 48,723 customers. These features are essential for capturing dynamic behavioral patterns that static demographic data may miss.</p>
<ul>
<li><p><strong>Recency</strong>: Calculated as the number of days between the customer’s last transaction and the reference date of <strong>December 30, 2023</strong>.</p></li>
<li><p><strong>Frequency</strong>: The total number of transactions recorded for each customer throughout the 12-month period.</p></li>
<li><p><strong>Monetary</strong>: The total value of all transactions in Colombian Pesos (COP) for each individual customer.</p></li>
</ul>
<p>By aggregating over 3.1 million transaction-level rows into these three customer-level dimensions, I can better identify high-value loyalists and distinguish them from at-risk users, providing a more robust foundation for churn prediction.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the reference date (one day after the last transaction in the dataset)</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>reference_date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="st">"2023-12-30"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate RFM metrics from transactions_data</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>rfm_features <span class="ot">&lt;-</span> transactions_data <span class="sc">%&gt;%</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Ensure the date column is in the correct Date format</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">date =</span> <span class="fu">as.Date</span>(date)) <span class="sc">%&gt;%</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(customer_id) <span class="sc">%&gt;%</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Recency: Days since the last transaction</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">recency =</span> <span class="fu">as.numeric</span>(reference_date <span class="sc">-</span> <span class="fu">max</span>(date)),</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Frequency: Total count of transactions</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">frequency =</span> <span class="fu">n</span>(),</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Monetary: Total sum of transaction amounts (in COP)</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">monetary =</span> <span class="fu">sum</span>(amount, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="merge-rfm-features-with-cleaned-customer-dataset" class="level5">
<h5 class="anchored" data-anchor-id="merge-rfm-features-with-cleaned-customer-dataset">3.3.2.2 Merge RFM features with cleaned customer dataset</h5>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge RFM features with your cleaned customer dataset</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>customer_data_final <span class="ot">&lt;-</span> customer_data_clean <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(rfm_features, <span class="at">by =</span> <span class="st">"customer_id"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize missingness in customer data</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gg_miss_var</span>(customer_data_final)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Every customer has a Recency, Frequency, and Monetary value.</p>
</section>
<section id="statistical-summary-of-data" class="level5">
<h5 class="anchored" data-anchor-id="statistical-summary-of-data">3.3.2.3 Statistical Summary of Data</h5>
<p>I use <code>skim()</code> because standard functions like <code>summary()</code> or <code>str()</code> become an unreadable wall of text when we have 57 variables.</p>
<p>Here is exactly why it is the most efficient choice for a wide dataset:</p>
<ul>
<li><p><strong>Instant Organization:</strong> It automatically groups the 57 variables by data type (numeric, character, factor, etc.) into clean, separate tables, making the output much easier to navigate.</p></li>
<li><p><strong>Inline Distributions:</strong> For numeric data, it generates tiny inline histograms (sparklines) directly in the console. This lets us spot skewed distributions, outliers, or weird patterns at a glance without having to plot dozens of individual charts.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>customer_data_final <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">skim</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">Piped data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">48723</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">57</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Date</td>
<td style="text-align: left;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">logical</td>
<td style="text-align: left;">7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">32</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 31%">
<col style="width: 11%">
<col style="width: 16%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">gender</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">location</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">income_bracket</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">occupation</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">education_level</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">marital_status</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">acquisition_channel</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">customer_segment</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">feedback_sentiment</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">feature_requests</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">complaint_topics</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">clv_segment</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">preferred_transaction_type</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: Date</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 25%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: left;">min</th>
<th style="text-align: left;">max</th>
<th style="text-align: left;">median</th>
<th style="text-align: right;">n_unique</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">first_tx</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">2023-01-04</td>
<td style="text-align: left;">2023-08-10</td>
<td style="text-align: left;">2023-01-14</td>
<td style="text-align: right;">180</td>
</tr>
<tr class="even">
<td style="text-align: left;">last_tx</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">2023-05-11</td>
<td style="text-align: left;">2023-12-29</td>
<td style="text-align: left;">2023-12-19</td>
<td style="text-align: right;">174</td>
</tr>
<tr class="odd">
<td style="text-align: left;">last_survey_date</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">2023-01-01</td>
<td style="text-align: left;">2023-12-31</td>
<td style="text-align: left;">2023-07-03</td>
<td style="text-align: right;">365</td>
</tr>
<tr class="even">
<td style="text-align: left;">last_transaction_date</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">2023-05-11</td>
<td style="text-align: left;">2023-12-29</td>
<td style="text-align: left;">2023-12-19</td>
<td style="text-align: right;">174</td>
</tr>
<tr class="odd">
<td style="text-align: left;">first_transaction_date</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">2023-01-04</td>
<td style="text-align: left;">2023-08-10</td>
<td style="text-align: left;">2023-01-14</td>
<td style="text-align: right;">180</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: logical</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 28%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 6%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: left;">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">savings_account</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: left;">TRU: 38459, FAL: 10264</td>
</tr>
<tr class="even">
<td style="text-align: left;">credit_card</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.63</td>
<td style="text-align: left;">TRU: 30460, FAL: 18263</td>
</tr>
<tr class="odd">
<td style="text-align: left;">personal_loan</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.32</td>
<td style="text-align: left;">FAL: 33321, TRU: 15402</td>
</tr>
<tr class="even">
<td style="text-align: left;">investment_account</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.43</td>
<td style="text-align: left;">FAL: 27985, TRU: 20738</td>
</tr>
<tr class="odd">
<td style="text-align: left;">insurance_product</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: left;">FAL: 38388, TRU: 10335</td>
</tr>
<tr class="even">
<td style="text-align: left;">bill_payment_user</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.70</td>
<td style="text-align: left;">TRU: 34170, FAL: 14553</td>
</tr>
<tr class="odd">
<td style="text-align: left;">auto_savings_enabled</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: left;">FAL: 29173, TRU: 19550</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">customer_id</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">55027986.01</td>
<td style="text-align: right;">2.592111e+07</td>
<td style="text-align: right;">10000617.00</td>
<td style="text-align: right;">32708345.50</td>
<td style="text-align: right;">55174470.00</td>
<td style="text-align: right;">77242332.00</td>
<td style="text-align: right;">9.999980e+07</td>
<td style="text-align: left;">▇▇▇▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">age</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">44.54</td>
<td style="text-align: right;">1.228000e+01</td>
<td style="text-align: right;">29.00</td>
<td style="text-align: right;">30.00</td>
<td style="text-align: right;">45.00</td>
<td style="text-align: right;">59.00</td>
<td style="text-align: right;">6.000000e+01</td>
<td style="text-align: left;">▇▁▇▁▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">household_size</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.50</td>
<td style="text-align: right;">1.580000e+00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">1.300000e+01</td>
<td style="text-align: left;">▇▅▂▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">active_products</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.10</td>
<td style="text-align: right;">1.180000e+00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">5.000000e+00</td>
<td style="text-align: left;">▇▆▃▂▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">app_logins_frequency</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">22.38</td>
<td style="text-align: right;">1.175000e+01</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">15.00</td>
<td style="text-align: right;">22.00</td>
<td style="text-align: right;">30.00</td>
<td style="text-align: right;">1.000000e+02</td>
<td style="text-align: left;">▇▅▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">feature_usage_diversity</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.37</td>
<td style="text-align: right;">1.740000e+00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">1.000000e+01</td>
<td style="text-align: left;">▇▅▂▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">credit_utilization_ratio</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">1.900000e-01</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: right;">9.400000e-01</td>
<td style="text-align: left;">▇▃▂▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">international_transactions</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.49</td>
<td style="text-align: right;">7.000000e-01</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">6.000000e+00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">failed_transactions</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">4.400000e-01</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">4.000000e+00</td>
<td style="text-align: left;">▇▂▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">tx_count</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">64.84</td>
<td style="text-align: right;">6.119300e+02</td>
<td style="text-align: right;">10.00</td>
<td style="text-align: right;">12.00</td>
<td style="text-align: right;">18.00</td>
<td style="text-align: right;">35.00</td>
<td style="text-align: right;">7.746500e+04</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">avg_tx_value</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3564851.69</td>
<td style="text-align: right;">3.959443e+06</td>
<td style="text-align: right;">318215.00</td>
<td style="text-align: right;">1339114.49</td>
<td style="text-align: right;">1763107.41</td>
<td style="text-align: right;">4658536.36</td>
<td style="text-align: right;">5.167030e+07</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">total_tx_volume</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">257472847.91</td>
<td style="text-align: right;">6.211110e+09</td>
<td style="text-align: right;">3182150.00</td>
<td style="text-align: right;">20158450.00</td>
<td style="text-align: right;">48081150.00</td>
<td style="text-align: right;">120445000.00</td>
<td style="text-align: right;">1.073087e+12</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">base_satisfaction</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">8.00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: right;">4.25</td>
<td style="text-align: right;">7.33</td>
<td style="text-align: right;">8.01</td>
<td style="text-align: right;">8.68</td>
<td style="text-align: right;">1.194000e+01</td>
<td style="text-align: left;">▁▃▇▂▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">tx_satisfaction</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">2.200000e-01</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">product_satisfaction</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">2.300000e-01</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">0.60</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: left;">▆▇▇▃▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">satisfaction_score</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.16</td>
<td style="text-align: right;">5.800000e-01</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">6.000000e+00</td>
<td style="text-align: left;">▁▁▇▃▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">nps_score</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-26.76</td>
<td style="text-align: right;">1.256000e+01</td>
<td style="text-align: right;">-80.00</td>
<td style="text-align: right;">-34.00</td>
<td style="text-align: right;">-28.00</td>
<td style="text-align: right;">-19.00</td>
<td style="text-align: right;">2.300000e+01</td>
<td style="text-align: left;">▁▂▇▃▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">support_tickets_count</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">7.000000e+00</td>
<td style="text-align: left;">▇▂▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">resolved_tickets_ratio</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.51</td>
<td style="text-align: right;">4.800000e-01</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: left;">▇▁▁▁▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">app_store_rating</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.16</td>
<td style="text-align: right;">5.900000e-01</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">4.50</td>
<td style="text-align: right;">5.000000e+00</td>
<td style="text-align: left;">▁▁▃▆▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">monthly_transaction_count</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5.77</td>
<td style="text-align: right;">5.097000e+01</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.60</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">3.09</td>
<td style="text-align: right;">6.455420e+03</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">average_transaction_value</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3564851.69</td>
<td style="text-align: right;">3.959443e+06</td>
<td style="text-align: right;">318215.00</td>
<td style="text-align: right;">1339114.49</td>
<td style="text-align: right;">1763107.41</td>
<td style="text-align: right;">4658536.36</td>
<td style="text-align: right;">5.167030e+07</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">total_transaction_volume</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">257472847.91</td>
<td style="text-align: right;">6.211110e+09</td>
<td style="text-align: right;">3182150.00</td>
<td style="text-align: right;">20158450.00</td>
<td style="text-align: right;">48081150.00</td>
<td style="text-align: right;">120445000.00</td>
<td style="text-align: right;">1.073087e+12</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">transaction_frequency</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: right;">1.700000e+00</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">2.157800e+02</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">weekend_transaction_ratio</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">1.000000e-01</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">9.100000e-01</td>
<td style="text-align: left;">▂▇▂▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">avg_daily_transactions</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: right;">1.700000e+00</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">2.157800e+02</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">customer_tenure</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">11.37</td>
<td style="text-align: right;">7.200000e-01</td>
<td style="text-align: right;">4.70</td>
<td style="text-align: right;">11.17</td>
<td style="text-align: right;">11.63</td>
<td style="text-align: right;">11.87</td>
<td style="text-align: right;">1.197000e+01</td>
<td style="text-align: left;">▁▁▁▁▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">churn_probability</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">7.000000e-02</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">0.35</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">5.000000e-01</td>
<td style="text-align: left;">▁▂▆▇▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">customer_lifetime_value</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">328159670.79</td>
<td style="text-align: right;">7.926224e+08</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">58414383.33</td>
<td style="text-align: right;">129681954.23</td>
<td style="text-align: right;">297355900.21</td>
<td style="text-align: right;">1.776860e+10</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">recency</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">18.74</td>
<td style="text-align: right;">2.170000e+01</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">11.00</td>
<td style="text-align: right;">25.00</td>
<td style="text-align: right;">2.330000e+02</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">frequency</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">64.84</td>
<td style="text-align: right;">6.119300e+02</td>
<td style="text-align: right;">10.00</td>
<td style="text-align: right;">12.00</td>
<td style="text-align: right;">18.00</td>
<td style="text-align: right;">35.00</td>
<td style="text-align: right;">7.746500e+04</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">monetary</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">257472847.91</td>
<td style="text-align: right;">6.211110e+09</td>
<td style="text-align: right;">3182150.00</td>
<td style="text-align: right;">20158450.00</td>
<td style="text-align: right;">48081150.00</td>
<td style="text-align: right;">120445000.00</td>
<td style="text-align: right;">1.073087e+12</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
</section>
</section>
<section id="analytical-workflow" class="level2">
<h2 class="anchored" data-anchor-id="analytical-workflow">4 Analytical Workflow</h2>
<p>The analytical workflow follows a systematic pipeline: initial <strong>feature engineering</strong> and <strong>variable selection</strong> to refine the high-dimensional dataset, followed by <strong>univariate distribution analysis</strong> to identify outliers. A <strong>correlation matrix</strong> is then utilized to detect initial pairwise multi-collinearity among the behavioral metrics. The data is subsequently partitioned through <strong>random sampling</strong> into training and testing sets. Finally, a <strong>Variance Inflation Factor (VIF)</strong> assessment is applied strictly to the training data to detect and eliminate any remaining multivariate collinearity before the <strong>predictive models</strong> are developed.</p>
<section id="feature-engineering-and-variable-selection" class="level3">
<h3 class="anchored" data-anchor-id="feature-engineering-and-variable-selection">4.1 Feature Engineering and Variable Selection</h3>
<p>To enhance model parsimony and mitigate the risks associated with high cardinality, categorical variables—specifically <strong>location</strong>, <strong>occupation</strong>, and <strong>feature_requests</strong>—were subjected to frequency-based lumping. Utilizing the <code>fct_lump_n</code> function, the feature space for each variable was condensed to preserve only the five most frequent levels, with all remaining infrequent categories consolidated into a standardized ‘Other’ designation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Applying lumping to location, occupation, and feature_requests</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>modeling_data <span class="ot">&lt;-</span> customer_data_final <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Preserve top 5 most frequent locations</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">location =</span> <span class="fu">fct_lump_n</span>(<span class="fu">as.factor</span>(location), <span class="at">n =</span> <span class="dv">5</span>, <span class="at">other_level =</span> <span class="st">"Other"</span>),</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Preserve top 5 most frequent occupations</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">occupation =</span> <span class="fu">fct_lump_n</span>(<span class="fu">as.factor</span>(occupation), <span class="at">n =</span> <span class="dv">5</span>, <span class="at">other_level =</span> <span class="st">"Other"</span>),</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Preserve top 5 feature requests</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">feature_requests =</span> <span class="fu">fct_lump_n</span>(<span class="fu">as.factor</span>(feature_requests), <span class="at">n =</span> <span class="dv">5</span>, <span class="at">other_level =</span> <span class="st">"Other"</span>)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>To account for the duration of the customer relationship, a <strong>Tenure</strong> variable was engineered by calculating the chronological distance between each customer’s <code>first_transaction_date</code> and the study’s reference date of December 30, 2023. In contrast to the provided <code>customer_tenure</code> variable, which is measured in months, this daily calculation offers a high-granularity perspective on the customer lifecycle. This enables the model to more accurately identify churn risks within critical windows, such as the early onboarding phase or the transition into long-term loyalty.”</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reference date based on the 2023 dataset cutoff</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>ref_date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="st">"2023-12-30"</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>modeling_data <span class="ot">&lt;-</span> modeling_data <span class="sc">%&gt;%</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Ensure first_transaction_date is in Date format</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">first_transaction_date =</span> <span class="fu">as.Date</span>(first_transaction_date),</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate Tenure in days</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">tenure =</span> <span class="fu">as.numeric</span>(ref_date <span class="sc">-</span> first_transaction_date)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Prior to model training, a rigorous feature selection process was conducted to ensure model parsimony and prevent multicollinearity. The following table details the variables excluded from the final dataset, along with the specific technical or behavioral justification for their removal.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the R code used to generate this table</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>excluded_vars <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variable =</span> <span class="fu">c</span>(</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"customer_id"</span>, </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"last_tx / last_transaction_date"</span>, </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"first_tx / first_transaction_date"</span>,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"last_survey_date"</span>,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"satisfaction_score"</span>,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"avg_tx_value"</span>,</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"monthly_transaction_count"</span>,</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"average_transaction_value"</span>,</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"tx_count"</span>,</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"total_tx_volume"</span>,</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"total_transaction_volume"</span>,</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"transaction_frequency"</span>,</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"avg_daily_transactions"</span>,</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"customer_tenure"</span>,</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"clv_segment"</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">Reason_for_Exclusion =</span> <span class="fu">c</span>(</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Zero predictive power; random identifier with no relationship to financial behavior."</span>,</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Redundant; information captured by the engineered 'Recency' feature."</span>,</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Redundant; information captured by the engineered 'Tenure' feature."</span>,</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Sentiment signal is better captured by satisfaction pillars or NPS; dates are less predictive than scores."</span>,</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Excluded to prioritize model interpretability; specific pillars (base, tx, product) provide more actionable insights."</span>,</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">"High multicollinearity with total_tx_volume."</span>,</span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">"High multicollinearity with tx_count."</span>,</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Redundant; mathematically derived from monetary and frequency."</span>,</span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Redundant; information captured by the engineered 'frequency' feature."</span>,</span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Redundant; information captured by the engineered 'monetary' feature."</span>,</span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Data inconsistency; shares a definition with total_tx_volume but contains significant system noise."</span>,</span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a>    <span class="st">"High correlation with frequency."</span>,</span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Perfectly correlated with frequency (mathematical derivative)."</span>,</span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Redundant; information captured by the higher-granularity 'Tenure' (days) feature."</span>,</span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Categorical derivative of customer_lifetime_value; removed to preserve raw numeric granularity for the model."</span></span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-37"><a href="#cb12-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-38"><a href="#cb12-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Render the table</span></span>
<span id="cb12-39"><a href="#cb12-39" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb12-40"><a href="#cb12-40" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(excluded_vars, </span>
<span id="cb12-41"><a href="#cb12-41" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Variable"</span>, <span class="st">"Rationale for Exclusion"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb12-42"><a href="#cb12-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>, <span class="st">"condensed"</span>), </span>
<span id="cb12-43"><a href="#cb12-43" aria-hidden="true" tabindex="-1"></a>                <span class="at">full_width =</span> F) <span class="sc">%&gt;%</span></span>
<span id="cb12-44"><a href="#cb12-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_spec</span>(<span class="dv">1</span>, <span class="at">bold =</span> T, <span class="at">border_right =</span> T) <span class="sc">%&gt;%</span></span>
<span id="cb12-45"><a href="#cb12-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_spec</span>(<span class="dv">2</span>, <span class="at">width =</span> <span class="st">"35em"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-excluded" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-excluded-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Summary of Excluded Variables and Rationalization
</figcaption>
<div aria-describedby="tbl-excluded-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed do-not-create-environment cell caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Rationale for Exclusion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">customer_id</td>
<td style="text-align: left; width: 35em;">Zero predictive power; random identifier with no relationship to financial behavior.</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">last_tx / last_transaction_date</td>
<td style="text-align: left; width: 35em;">Redundant; information captured by the engineered 'Recency' feature.</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">first_tx / first_transaction_date</td>
<td style="text-align: left; width: 35em;">Redundant; information captured by the engineered 'Tenure' feature.</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">last_survey_date</td>
<td style="text-align: left; width: 35em;">Sentiment signal is better captured by satisfaction pillars or NPS; dates are less predictive than scores.</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">satisfaction_score</td>
<td style="text-align: left; width: 35em;">Excluded to prioritize model interpretability; specific pillars (base, tx, product) provide more actionable insights.</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">avg_tx_value</td>
<td style="text-align: left; width: 35em;">High multicollinearity with total_tx_volume.</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">monthly_transaction_count</td>
<td style="text-align: left; width: 35em;">High multicollinearity with tx_count.</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">average_transaction_value</td>
<td style="text-align: left; width: 35em;">Redundant; mathematically derived from monetary and frequency.</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">tx_count</td>
<td style="text-align: left; width: 35em;">Redundant; information captured by the engineered 'frequency' feature.</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">total_tx_volume</td>
<td style="text-align: left; width: 35em;">Redundant; information captured by the engineered 'monetary' feature.</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">total_transaction_volume</td>
<td style="text-align: left; width: 35em;">Data inconsistency; shares a definition with total_tx_volume but contains significant system noise.</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">transaction_frequency</td>
<td style="text-align: left; width: 35em;">High correlation with frequency.</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">avg_daily_transactions</td>
<td style="text-align: left; width: 35em;">Perfectly correlated with frequency (mathematical derivative).</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">customer_tenure</td>
<td style="text-align: left; width: 35em;">Redundant; information captured by the higher-granularity 'Tenure' (days) feature.</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">clv_segment</td>
<td style="text-align: left; width: 35em;">Categorical derivative of customer_lifetime_value; removed to preserve raw numeric granularity for the model.</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Finalizing the modeling dataset by excluding 17 redundant or low-predictive variables</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>modeling_data <span class="ot">&lt;-</span> modeling_data <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span>customer_id,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span>last_tx, <span class="sc">-</span>last_transaction_date,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span>first_tx, <span class="sc">-</span>first_transaction_date,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span>last_survey_date,</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span>satisfaction_score,            </span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span>avg_tx_value,</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span>monthly_transaction_count,</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span>average_transaction_value,</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span>tx_count,</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span>total_tx_volume,</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span>total_transaction_volume,</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span>transaction_frequency,</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span>avg_daily_transactions,</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span>customer_tenure,</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span>clv_segment</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="univariate-distribution-analysis" class="level3">
<h3 class="anchored" data-anchor-id="univariate-distribution-analysis">4.2 Univariate distribution Analysis</h3>
<section id="distribution-of-target-variable" class="level4">
<h4 class="anchored" data-anchor-id="distribution-of-target-variable">4.2.1 Distribution of Target Variable</h4>
<p>Combining a histogram with a density curve provides the most comprehensive view of the overall distribution for the <code>churn_probability</code>. The histogram reveals the granular details and exact data bins, highlighting specific spikes or gaps in the actual risk scores. Meanwhile, the overlaid density curve smooths out this noise, allowing us to instantly identify the overarching shape and trends of the customer baseline risk.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href="">Plot</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false" href="">Code</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(modeling_data, <span class="fu">aes</span>(<span class="at">x =</span> churn_probability)) <span class="sc">+</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> ..density..), <span class="at">bins =</span> <span class="dv">30</span>, <span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>, <span class="at">fill =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Univariate Distribution of Churn Probability"</span>,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Understanding the baseline risk across the customer base"</span>,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Churn Probability (0 to 1)"</span>,</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Density"</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate specific risk tiers</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>risk_tiers <span class="ot">&lt;-</span> <span class="fu">quantile</span>(modeling_data<span class="sc">$</span>churn_probability, <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.75</span>, <span class="fl">0.90</span>, <span class="fl">0.99</span>))</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(risk_tiers)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      75%       90%       99% 
0.3927236 0.4200311 0.4632467 </code></pre>
</div>
</div>
<p>The distribution of <code>churn_probability</code> is notably compressed, with a maximum value of <strong>0.5006</strong>. Because the vast majority of the population falls below the traditional <strong>0.50</strong> classification threshold, a standard binary approach would result in significant ‘under-counting’ of at-risk individuals. To address this, a <strong>Relative Risk Framework</strong> was adopted. The <strong>75th percentile (0.3927)</strong> was used to identify the transition into ‘Medium Risk,’ while the <strong>90th percentile (0.4200)</strong> was established as the operational threshold for ‘High Risk’ classification. This approach ensures the model identifies the most vulnerable <strong>10%</strong> of the customer base, providing actionable targets for the bank’s retention strategies by focusing on the highest relative risk.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Defining Risk Tiers based on calculated percentiles</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>modeling_data <span class="ot">&lt;-</span> modeling_data <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">risk_group =</span> <span class="fu">case_when</span>(</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    churn_probability <span class="sc">&gt;=</span> <span class="fl">0.4200</span> <span class="sc">~</span> <span class="st">"High Risk (&gt;90th)"</span>,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    churn_probability <span class="sc">&gt;=</span> <span class="fl">0.3927</span> <span class="sc">~</span> <span class="st">"Medium Risk (75th-90th)"</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Standard (&lt;75th)"</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Ensuring factor levels are ordered for logical plotting</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">risk_group =</span> <span class="fu">factor</span>(risk_group, </span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>                             <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Standard (&lt;75th)"</span>, </span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Medium Risk (75th-90th)"</span>, </span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"High Risk (&gt;90th)"</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="distribution-of-numerical-variables" class="level4">
<h4 class="anchored" data-anchor-id="distribution-of-numerical-variables">4.2.2 Distribution of Numerical Variables</h4>
<p>I used faceted boxplots to efficiently visualize the distribution and spread of all the numerical variables simultaneously, regardless of their differing scales. This visual approach allows us to instantly identify data anomalies, as it automatically isolates and flags potential outliers falling beyond 1.5 times the Interquartile Range (IQR) in red.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true" href="">Plot</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false" href="">Code</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div class="cell">
<div class="cell-output-display">
<div id="fig-outlier-detection" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-outlier-detection-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Take-home_Ex02_files/figure-html/fig-outlier-detection-1.png" class="img-fluid figure-img" width="1344">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-outlier-detection-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Outlier detection for all numerical features
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify all numeric variables</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>numeric_cols <span class="ot">&lt;-</span> modeling_data <span class="sc">%&gt;%</span> </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">%&gt;%</span> </span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">colnames</span>()</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshape data for a facet-grid boxplot</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>modeling_data <span class="sc">%&gt;%</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">all_of</span>(numeric_cols)) <span class="sc">%&gt;%</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">"variable"</span>, <span class="at">values_to =</span> <span class="st">"value"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> variable, <span class="at">y =</span> value)) <span class="sc">+</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">outlier.color =</span> <span class="st">"red"</span>, <span class="at">outlier.shape =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>variable, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span> <span class="co"># 'free' is key because scales differ</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Outlier Detection Across Numerical Variables"</span>,</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Red dots indicate potential outliers beyond 1.5 * IQR"</span>) <span class="sc">+</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_blank</span>()) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
<p>To balance model stability with data preservation, <strong>Winsorization</strong> was applied to the behavioral features <strong>monetary</strong>, <strong>frequency</strong>, and <strong>customer_lifetime_value</strong>. Rather than excluding these high-value data points, extreme outliers were capped at the <strong>99th percentile</strong>. This approach mitigates the influence of extreme variance on tree-splitting algorithms while ensuring that the predictive model retains critical insights from the bank’s most significant customer segments, leading to more robust and generalizable results.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Finalizing the Behavioral Features</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>vars_to_cap <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"monetary"</span>, <span class="st">"frequency"</span>, <span class="st">"customer_lifetime_value"</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>modeling_data <span class="ot">&lt;-</span> modeling_data <span class="sc">%&gt;%</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">all_of</span>(vars_to_cap), <span class="sc">~</span> {</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    upper_limit <span class="ot">&lt;-</span> <span class="fu">quantile</span>(.x, <span class="fl">0.99</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ifelse</span>(.x <span class="sc">&gt;</span> upper_limit, upper_limit, .x)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  }))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="correlation-matrix" class="level3">
<h3 class="anchored" data-anchor-id="correlation-matrix">4.3 Correlation Matrix</h3>
<p>I use <code>corrplot</code> to instantly visualize the strength and direction of relationships between all the numeric variables, making it easy to spot potential multicollinearity before modeling. By using hierarchical clustering (<code>order = "hclust"</code>), the plot automatically groups highly correlated variables together so patterns stand out naturally. Furthermore, overlaying the exact numbers (<code>addCoef.col</code>) gives us the precise correlation coefficients alongside the color-coded heatmap, providing both a big-picture summary and granular detail in a single chart.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true" href="">Plot</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false" href="">Code</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Isolate numeric variables </span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>numeric_vars <span class="ot">&lt;-</span> modeling_data <span class="sc">%&gt;%</span> </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric))</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Compute the matrix</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(numeric_vars, <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Render with Numbers</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(cor_matrix, </span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">method =</span> <span class="st">"color"</span>, </span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">type =</span> <span class="st">"upper"</span>, </span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">order =</span> <span class="st">"hclust"</span>, </span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">addCoef.col =</span> <span class="st">"black"</span>, <span class="co"># This adds the correlation numbers</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>         <span class="at">number.cex =</span> <span class="fl">0.4</span>,      <span class="co"># Crucial: tiny font so 42x42 numbers fit</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">tl.col =</span> <span class="st">"black"</span>, </span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">tl.srt =</span> <span class="dv">45</span>, </span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">tl.cex =</span> <span class="fl">0.5</span>, </span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>         <span class="at">diag =</span> <span class="cn">FALSE</span>, </span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>         <span class="at">title =</span> <span class="st">"</span><span class="sc">\n\n</span><span class="st">Correlation Matrix with Coefficients"</span>,</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>         <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">3</span>,<span class="dv">0</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
<p>The feature set was refined to ensure model integrity and transition from descriptive to predictive analysis. <code>monetary</code> and <code>base_satisfaction</code> were removed to resolve multicollinearity, as they were highly redundant with <code>customer_lifetime_value</code> (<span class="math inline">\(r = 0.96\)</span>) and <code>nps_score</code> (<span class="math inline">\(r = 0.78\)</span>), respectively. Additionally, <code>risk_group</code> and <code>active_products</code> were excluded to eliminate data leakage. Because <code>active_products</code> acted as a lagging mathematical proxy for the target (<span class="math inline">\(r = -0.88\)</span>), its removal forced the model to rely on proactive behavioral signals—such as app engagement and sentiment—that allow for genuine early intervention.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Finalizing the features by removing leaky and redundant variables</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>modeling_data_final <span class="ot">&lt;-</span> modeling_data <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span>monetary,        <span class="co"># Removed due to high multicollinearity (r = 0.96) with CLV</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span>risk_group,      <span class="co"># Removed to prevent leakage (directly derived from target)</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span>active_products,  <span class="co"># Removed as a lagging indicator (r = -0.88 with target)</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span>base_satisfaction   <span class="co"># Redundant with nps_score (r = 0.78)</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># List final column names </span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(modeling_data_final)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<details>
<summary>
Click to reveal final column names
</summary>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] "age"                        "gender"                    
 [3] "location"                   "income_bracket"            
 [5] "occupation"                 "education_level"           
 [7] "marital_status"             "household_size"            
 [9] "acquisition_channel"        "customer_segment"          
[11] "savings_account"            "credit_card"               
[13] "personal_loan"              "investment_account"        
[15] "insurance_product"          "app_logins_frequency"      
[17] "feature_usage_diversity"    "bill_payment_user"         
[19] "auto_savings_enabled"       "credit_utilization_ratio"  
[21] "international_transactions" "failed_transactions"       
[23] "tx_satisfaction"            "product_satisfaction"      
[25] "nps_score"                  "support_tickets_count"     
[27] "resolved_tickets_ratio"     "app_store_rating"          
[29] "feedback_sentiment"         "feature_requests"          
[31] "complaint_topics"           "preferred_transaction_type"
[33] "weekend_transaction_ratio"  "churn_probability"         
[35] "customer_lifetime_value"    "recency"                   
[37] "frequency"                  "tenure"                    </code></pre>
</div>
</div>
</details>
</section>
<section id="stratified-random-sampling" class="level3">
<h3 class="anchored" data-anchor-id="stratified-random-sampling">4.4 Stratified Random Sampling</h3>
<p>To evaluate model performance and generalizability, the finalized dataset was partitioned using <strong>stratified random sampling</strong>. An <strong>80/20 split</strong> was implemented, resulting in a training set of approximately 39,000 observations and a holdout testing set of 9,700 observations. Stratification was applied to the <code>churn_probability</code> target to ensure that both subsets maintained an identical risk distribution, providing a robust foundation for the subsequent training phase.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility (so you get the same 'random' split every time)</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the split (80% Training, 20% Testing)</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co"># We stratify by churn_probability to keep the risk distribution consistent</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>data_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(modeling_data_final, </span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>                           <span class="at">prop =</span> <span class="fl">0.80</span>, </span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>                           <span class="at">strata =</span> churn_probability)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Extract the sets</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> <span class="fu">training</span>(data_split)</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>test_data  <span class="ot">&lt;-</span> <span class="fu">testing</span>(data_split)</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Verify the split sizes</span></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(train_data) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 38976</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(test_data)  </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9747</code></pre>
</div>
</div>
</section>
<section id="variance-inflation-factor-vif" class="level3">
<h3 class="anchored" data-anchor-id="variance-inflation-factor-vif">4.5 Variance Inflation Factor (VIF)</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>my_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(churn_probability <span class="sc">~</span> ., <span class="at">data =</span> train_data)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="co"># This will show you the exact variables that are perfectly correlated</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">alias</span>(my_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<details>
<summary>
Click to reveal <em>Perfect</em> Multicollinearity
</summary>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Model :
churn_probability ~ age + gender + location + income_bracket + 
    occupation + education_level + marital_status + household_size + 
    acquisition_channel + customer_segment + savings_account + 
    credit_card + personal_loan + investment_account + insurance_product + 
    app_logins_frequency + feature_usage_diversity + bill_payment_user + 
    auto_savings_enabled + credit_utilization_ratio + international_transactions + 
    failed_transactions + tx_satisfaction + product_satisfaction + 
    nps_score + support_tickets_count + resolved_tickets_ratio + 
    app_store_rating + feedback_sentiment + feature_requests + 
    complaint_topics + preferred_transaction_type + weekend_transaction_ratio + 
    customer_lifetime_value + recency + frequency + tenure

Complete :
                     (Intercept) age genderMale genderOther
product_satisfaction   0           0   0          0        
                     locationBogotá, Cundinamarca locationCali, Valle del Cauca
product_satisfaction   0                            0                          
                     locationCartagena, Bolívar locationMedellín, Antioquia
product_satisfaction   0                          0                        
                     locationOther income_bracketLow income_bracketMedium
product_satisfaction   0             0                 0                 
                     income_bracketVery High occupationDesigner
product_satisfaction   0                       0               
                     occupationHairdresser occupationMechanic
product_satisfaction   0                     0               
                     occupationPolice Officer occupationOther
product_satisfaction   0                        0            
                     education_levelHigh School education_levelMaster
product_satisfaction   0                          0                  
                     education_levelPhD marital_statusMarried
product_satisfaction   0                  0                  
                     marital_statusSingle marital_statusWidowed household_size
product_satisfaction   0                    0                     0           
                     acquisition_channelPaid Ad acquisition_channelPartnership
product_satisfaction   0                          0                           
                     acquisition_channelReferral customer_segmentoccasional
product_satisfaction   0                           0                       
                     customer_segmentpower customer_segmentregular
product_satisfaction   0                     0                    
                     savings_accountTRUE credit_cardTRUE personal_loanTRUE
product_satisfaction 1/5                 1/5             1/5              
                     investment_accountTRUE insurance_productTRUE
product_satisfaction 1/5                    1/5                  
                     app_logins_frequency feature_usage_diversity
product_satisfaction   0                    0                    
                     bill_payment_userTRUE auto_savings_enabledTRUE
product_satisfaction   0                     0                     
                     credit_utilization_ratio international_transactions
product_satisfaction   0                        0                       
                     failed_transactions tx_satisfaction nps_score
product_satisfaction   0                   0               0      
                     support_tickets_count resolved_tickets_ratio
product_satisfaction   0                     0                   
                     app_store_rating feedback_sentimentNeutral
product_satisfaction   0                0                      
                     feedback_sentimentPositive
product_satisfaction   0                       
                     feature_requestsCryptocurrency trading
product_satisfaction   0                                   
                     feature_requestsMobile check deposit
product_satisfaction   0                                 
                     feature_requestsNo Interaction
product_satisfaction   0                           
                     feature_requestsSavings goals feature_requestsOther
product_satisfaction   0                             0                  
                     complaint_topicsApp performance
product_satisfaction   0                            
                     complaint_topicsCustomer service complaint_topicsFees
product_satisfaction   0                                0                 
                     complaint_topicsNone complaint_topicsTransaction issues
product_satisfaction   0                    0                               
                     preferred_transaction_typePayment
product_satisfaction   0                              
                     preferred_transaction_typeTransfer
product_satisfaction   0                               
                     preferred_transaction_typeWithdrawal
product_satisfaction   0                                 
                     weekend_transaction_ratio customer_lifetime_value recency
product_satisfaction   0                         0                       0    
                     frequency tenure
product_satisfaction   0         0   </code></pre>
</div>
</div>
</details>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fits the model without the redundant average column</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>my_model_fixed <span class="ot">&lt;-</span> <span class="fu">lm</span>(churn_probability <span class="sc">~</span> . <span class="sc">-</span> product_satisfaction, <span class="at">data =</span> train_data)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate VIF</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(my_model_fixed)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<details>
<summary>
Click to reveal <em>VIF</em> result
</summary>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                               GVIF Df GVIF^(1/(2*Df))
age                        1.336399  1        1.156027
gender                     1.003020  2        1.000754
location                   1.007135  5        1.000711
income_bracket             2.197578  3        1.140225
occupation                 1.008060  5        1.000803
education_level            1.814235  3        1.104373
marital_status             1.004493  3        1.000747
household_size             1.001308  1        1.000654
acquisition_channel        1.004809  3        1.000800
customer_segment           1.785609  3        1.101449
savings_account            1.343910  1        1.159271
credit_card                2.517063  1        1.586525
personal_loan              1.180099  1        1.086324
investment_account         1.234918  1        1.111269
insurance_product          1.121690  1        1.059099
app_logins_frequency       1.001576  1        1.000788
feature_usage_diversity    1.815202  1        1.347294
bill_payment_user          1.001503  1        1.000751
auto_savings_enabled       1.001525  1        1.000762
credit_utilization_ratio   2.208119  1        1.485974
international_transactions 1.001362  1        1.000681
failed_transactions        1.001205  1        1.000602
tx_satisfaction            5.211323  1        2.282832
nps_score                  1.017656  1        1.008789
support_tickets_count      1.611396  1        1.269408
resolved_tickets_ratio     1.612656  1        1.269904
app_store_rating           2.912844  1        1.706705
feedback_sentiment         2.918243  2        1.307014
feature_requests           1.008109  5        1.000808
complaint_topics           1.007840  5        1.000781
preferred_transaction_type 1.004395  3        1.000731
weekend_transaction_ratio  1.001436  1        1.000718
customer_lifetime_value    4.010886  1        2.002720
recency                    1.135102  1        1.065412
frequency                  4.825732  1        2.196755
tenure                     1.141237  1        1.068287</code></pre>
</div>
</div>
</details>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove the variables from the training data</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> train_data <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>product_satisfaction, <span class="sc">-</span>tx_satisfaction)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove the EXACT SAME variables from the testing data</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> test_data <span class="sc">%&gt;%</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>product_satisfaction, <span class="sc">-</span>tx_satisfaction)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Remove perfect/high multicollinearity variables
</div>
</div>
<div class="callout-body-container callout-body">
<p>During the multicollinearity assessment on the training set, <code>product_satisfaction</code> was identified as having perfect multicollinearity (aliased), as it was an exact linear combination of the five individual banking product indicators. Consequently, it was removed to prevent information redundancy and distortion of feature importance. Subsequently, a Variance Inflation Factor (VIF) analysis was conducted, revealing that <code>tx_satisfaction</code> exceeded the conservative threshold of 5.0 (VIF = 5.21). To ensure strict model stability and maintain highly interpretable feature importance rankings for the final tree-based models (Random Forest and XGBoost), <code>tx_satisfaction</code> was also eliminated. To maintain feature alignment for model evaluation, these removals were identically applied to the testing dataset.</p>
</div>
</div>
</section>
</section>
<section id="building-predictive-models" class="level2">
<h2 class="anchored" data-anchor-id="building-predictive-models">5 Building Predictive Models</h2>
<p>For the predictive modeling phase, <strong>Random Forest</strong> and <strong>XGBoost</strong> were selected due to their superior ability to handle the non-linear relationships and complex feature interactions inherent in banking behavioral data. Random Forest provides a robust, ensemble-based baseline that reduces variance by averaging multiple decision trees, making it highly resistant to overfitting. In contrast, XGBoost (Extreme Gradient Boosting) was chosen for its iterative optimization process, which minimizes residual errors and typically yields higher precision in identifying subtle churn signals. Both models are natively capable of handling the mixed data types in this study—ranging from categorical sentiment scores to capped financial metrics—without requiring the strict linearity assumptions of traditional regression models.</p>
<section id="create-the-preprocessing-recipe" class="level3">
<h3 class="anchored" data-anchor-id="create-the-preprocessing-recipe">5.1 Create the Preprocessing Recipe</h3>
<p>This recipe will automatically clean the data for both models. Since we have categorical variables like <code>gender</code> and <code>occupation</code>, we must convert them into a numeric format (Dummy Encoding).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Building the recipe</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>churn_recipe <span class="ot">&lt;-</span> <span class="fu">recipe</span>(churn_probability <span class="sc">~</span> ., <span class="at">data =</span> train_data) <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Force logical/character columns to factors so they can be 'dummified'</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_mutate_at</span>(<span class="fu">all_nominal_predictors</span>(), <span class="fu">all_logical_predictors</span>(), <span class="at">fn =</span> as.factor) <span class="sc">%&gt;%</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create 0/1 numeric columns for all categorical/logical features</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_dummy</span>(<span class="fu">all_nominal_predictors</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Remove variables with zero variance</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_zv</span>(<span class="fu">all_predictors</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Normalize all numbers (optional but good practice)</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_normalize</span>(<span class="fu">all_numeric_predictors</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="tune-and-fit-the-models" class="level3">
<h3 class="anchored" data-anchor-id="tune-and-fit-the-models">5.2 Tune and Fit the Models</h3>
<section id="the-tuning-phase" class="level4">
<h4 class="anchored" data-anchor-id="the-tuning-phase">5.2.1 The Tuning Phase</h4>
<section id="set-up-cross-validation-folds" class="level5">
<h5 class="anchored" data-anchor-id="set-up-cross-validation-folds">5.2.1.1 Set Up Cross-Validation Folds</h5>
<p>Instead of training on the entire dataset at once, cross-validation splits training data into multiple “folds.” The model trains on a subset and evaluates on the holdout fold, repeating this process to ensure it generalizes well to unseen data.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create 5 folds for cross-validation </span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>) <span class="co"># For reproducibility</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>churn_folds <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(train_data, <span class="at">v =</span> <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="tag-hyperparameters-for-tuning" class="level5">
<h5 class="anchored" data-anchor-id="tag-hyperparameters-for-tuning">5.2.1.2 Tag Hyperparameters for Tuning</h5>
<ul>
<li><p><strong>For Random Forest:</strong> We typically tune <code>mtry</code> (number of predictors sampled at each split) and <code>min_n</code> (minimum data points in a node).</p></li>
<li><p><strong>For XGBoost:</strong> We typically tune <code>trees</code>, <code>learn_rate</code>, and <code>tree_depth</code>.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tunable Random Forest Spec</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>rf_tune_spec <span class="ot">&lt;-</span> <span class="fu">rand_forest</span>(</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">trees =</span> <span class="dv">500</span>, </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">mtry =</span> <span class="fu">tune</span>(), </span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">min_n =</span> <span class="fu">tune</span>()</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span>  </span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"ranger"</span>, <span class="at">importance =</span> <span class="st">"impurity"</span>) <span class="sc">%&gt;%</span>  </span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"regression"</span>)</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Tunable XGBoost Spec</span></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>xgb_tune_spec <span class="ot">&lt;-</span> <span class="fu">boost_tree</span>(</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">trees =</span> <span class="fu">tune</span>(), </span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">learn_rate =</span> <span class="fu">tune</span>(), </span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">tree_depth =</span> <span class="fu">tune</span>()</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span>  </span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"xgboost"</span>) <span class="sc">%&gt;%</span>  </span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"regression"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="build-the-tuning-workflows" class="level5">
<h5 class="anchored" data-anchor-id="build-the-tuning-workflows">5.2.1.3 Build the Tuning Workflows</h5>
<p>Attach recipe and the new tunable specifications to workflows.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>rf_tune_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span>  </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(churn_recipe) <span class="sc">%&gt;%</span>  </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(rf_tune_spec)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>xgb_tune_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span>  </span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(churn_recipe) <span class="sc">%&gt;%</span>  </span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(xgb_tune_spec)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="run-the-grid-search" class="level5">
<h5 class="anchored" data-anchor-id="run-the-grid-search">5.2.1.4 Run the Grid Search</h5>
<p>In this step, we perform hyperparameter tuning for both the Random Forest and XGBoost models. Using the 5 cross-validation folds created earlier, we test a grid of 5 distinct parameter combinations to identify the optimal settings that yield the lowest error rate.</p>
<p><strong>Note on Computation:</strong> Because grid search and cross-validation require training dozens of individual models, this process is highly computationally expensive. To prevent the Quarto document from taking an extensive amount of time to render, the code chunk below is set to <code>eval=FALSE</code>. The tuning was executed once locally, and the final result objects were saved as <code>.rds</code> (R Data) files. We will simply load these pre-computed results in the next step.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tune Random Forest</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">456</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>rf_tune_results <span class="ot">&lt;-</span> <span class="fu">tune_grid</span>(</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  rf_tune_wf,</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">resamples =</span> churn_folds,</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">grid =</span> <span class="dv">5</span> <span class="co"># Tests 5 different combinations</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Tune XGBoost</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">789</span>)</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>xgb_tune_results <span class="ot">&lt;-</span> <span class="fu">tune_grid</span>(</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>  xgb_tune_wf,</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">resamples =</span> churn_folds,</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">grid =</span> <span class="dv">5</span></span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(rf_tune_results, <span class="st">"rf_tune_results.rds"</span>)</span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(xgb_tune_results, <span class="st">"xgb_tune_results.rds"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Just load the finished results instantly:</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>rf_tune_results <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"rf_tune_results.rds"</span>)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>xgb_tune_results <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"xgb_tune_results.rds"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="the-finalizing-and-fitting-phase" class="level4">
<h4 class="anchored" data-anchor-id="the-finalizing-and-fitting-phase">5.2.2 The Finalizing and Fitting phase</h4>
<p>Once the tuning finishes, we can extract the best performing hyperparameter combination (e.g., the one with the lowest Root Mean Squared Error, or RMSE) and finalize the workflow.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the best parameters based on lowest RMSE</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>best_rf_params <span class="ot">&lt;-</span> <span class="fu">select_best</span>(rf_tune_results, <span class="at">metric =</span> <span class="st">"rmse"</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>best_xgb_params <span class="ot">&lt;-</span> <span class="fu">select_best</span>(xgb_tune_results, <span class="at">metric =</span> <span class="st">"rmse"</span>)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Plug those best parameters back into the workflows</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>final_rf_wf <span class="ot">&lt;-</span> <span class="fu">finalize_workflow</span>(rf_tune_wf, best_rf_params)</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>final_xgb_wf <span class="ot">&lt;-</span> <span class="fu">finalize_workflow</span>(xgb_tune_wf, best_xgb_params)</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Now you can fit these finalized models to full training data!</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>final_rf_fit <span class="ot">&lt;-</span> <span class="fu">fit</span>(final_rf_wf, <span class="at">data =</span> train_data)</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>final_xgb_fit <span class="ot">&lt;-</span> <span class="fu">fit</span>(final_xgb_wf, <span class="at">data =</span> train_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="model-performance-and-comparison" class="level3">
<h3 class="anchored" data-anchor-id="model-performance-and-comparison">5.3 Model Performance and Comparison</h3>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true" href="">Plot</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false" href="">Code</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Generate predictions on the test dataset</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="co"># augment() automatically attaches the predictions (.pred) to test data</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>rf_test_preds <span class="ot">&lt;-</span> <span class="fu">augment</span>(final_rf_fit, <span class="at">new_data =</span> test_data)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>xgb_test_preds <span class="ot">&lt;-</span> <span class="fu">augment</span>(final_xgb_fit, <span class="at">new_data =</span> test_data)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Define the metrics we want to calculate</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>churn_metrics <span class="ot">&lt;-</span> <span class="fu">metric_set</span>(rmse, rsq, mae)</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Calculate the metrics for Random Forest</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>rf_results <span class="ot">&lt;-</span> <span class="fu">churn_metrics</span>(rf_test_preds, <span class="at">truth =</span> churn_probability, <span class="at">estimate =</span> .pred) <span class="sc">%&gt;%</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">model =</span> <span class="st">"Random Forest"</span>)</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Calculate the metrics for XGBoost</span></span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>xgb_results <span class="ot">&lt;-</span> <span class="fu">churn_metrics</span>(xgb_test_preds, <span class="at">truth =</span> churn_probability, <span class="at">estimate =</span> .pred) <span class="sc">%&gt;%</span></span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">model =</span> <span class="st">"XGBoost"</span>)</span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a><span class="co"># 5. Combine the results into one clean comparison table</span></span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a>model_comparison <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(rf_results, xgb_results) <span class="sc">%&gt;%</span></span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(model, .metric, .estimate) <span class="sc">%&gt;%</span></span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(.metric, .estimate)</span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a faceted bar chart</span></span>
<span id="cb40-23"><a href="#cb40-23" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(model_comparison, <span class="fu">aes</span>(<span class="at">x =</span> model, <span class="at">y =</span> .estimate, <span class="at">fill =</span> model)) <span class="sc">+</span></span>
<span id="cb40-24"><a href="#cb40-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">width =</span> <span class="fl">0.6</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb40-25"><a href="#cb40-25" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add labels on top of bars for clarity</span></span>
<span id="cb40-26"><a href="#cb40-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(.estimate, <span class="dv">4</span>)), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="fl">3.5</span>) <span class="sc">+</span></span>
<span id="cb40-27"><a href="#cb40-27" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Split by metric and give each its own Y-axis scale</span></span>
<span id="cb40-28"><a href="#cb40-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> .metric, <span class="at">scales =</span> <span class="st">"free_y"</span>, </span>
<span id="cb40-29"><a href="#cb40-29" aria-hidden="true" tabindex="-1"></a>             <span class="at">labeller =</span> <span class="fu">labeller</span>(<span class="at">.metric =</span> <span class="fu">c</span>(</span>
<span id="cb40-30"><a href="#cb40-30" aria-hidden="true" tabindex="-1"></a>               <span class="at">mae =</span> <span class="st">"MAE"</span>, </span>
<span id="cb40-31"><a href="#cb40-31" aria-hidden="true" tabindex="-1"></a>               <span class="at">rmse =</span> <span class="st">"RMSE"</span>, </span>
<span id="cb40-32"><a href="#cb40-32" aria-hidden="true" tabindex="-1"></a>               <span class="at">rsq =</span> <span class="st">"R-Squared"</span></span>
<span id="cb40-33"><a href="#cb40-33" aria-hidden="true" tabindex="-1"></a>             ))) <span class="sc">+</span></span>
<span id="cb40-34"><a href="#cb40-34" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Clean up the look</span></span>
<span id="cb40-35"><a href="#cb40-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Random Forest"</span> <span class="ot">=</span> <span class="st">"#2c3e50"</span>, <span class="st">"XGBoost"</span> <span class="ot">=</span> <span class="st">"#e74c3c"</span>)) <span class="sc">+</span></span>
<span id="cb40-36"><a href="#cb40-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb40-37"><a href="#cb40-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Performance Comparison: Random Forest vs. XGBoost"</span>,</span>
<span id="cb40-38"><a href="#cb40-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb40-39"><a href="#cb40-39" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Metric Value"</span></span>
<span id="cb40-40"><a href="#cb40-40" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb40-41"><a href="#cb40-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb40-42"><a href="#cb40-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb40-43"><a href="#cb40-43" aria-hidden="true" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">11</span>),</span>
<span id="cb40-44"><a href="#cb40-44" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>)</span>
<span id="cb40-45"><a href="#cb40-45" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
<p>Overall, the <strong>Random Forest</strong> model marginally outperformed the XGBoost model across all evaluated metrics, making it the preferred model for this analysis.</p>
</section>
<section id="variable-importance-random-forest" class="level3">
<h3 class="anchored" data-anchor-id="variable-importance-random-forest">5.4 Variable Importance (Random Forest)</h3>
<p>To understand what drives the model’s predictions, we extract the variable importance scores from the finalized Random Forest model. These scores indicate how much each feature contributes to reducing the prediction error (measured by node impurity).</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-6-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-1" role="tab" aria-controls="tabset-6-1" aria-selected="true" href="">Plot</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-2" role="tab" aria-controls="tabset-6-2" aria-selected="false" href="">Code</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-6-1-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-6-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-2-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the fitted model from the workflow and generate the plot</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>final_rf_fit <span class="sc">%&gt;%</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_parsnip</span>() <span class="sc">%&gt;%</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">vip</span>(</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">num_features =</span> <span class="dv">10</span>, <span class="co"># Shows the top 15 most important variables</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">geom =</span> <span class="st">"col"</span>, </span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">aesthetics =</span> <span class="fu">list</span>(<span class="at">fill =</span> <span class="st">"#2c3e50"</span>) <span class="co"># Matches the color scheme from the previous plot</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Top 10 Most Important Variables: Random Forest"</span>,</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Importance Score"</span>,</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Predictor Variable"</span></span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>) <span class="co"># Makes variable names easier to read</span></span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpreting the Key Drivers of Churn
</div>
</div>
<div class="callout-body-container callout-body">
<p>We can group these primary drivers into four distinct business categories:</p>
<ul>
<li><p><strong>Demographics (<code>age</code>, <code>household_size</code>):</strong> Interestingly, <code>age</code> is the single most dominant predictor of churn in this dataset. This indicates that a customer’s life stage or generational cohort heavily dictates their likelihood of leaving the service. <code>household_size</code> also appears in the top 10, suggesting that family dynamics influence retention.</p></li>
<li><p><strong>Digital &amp; Transactional Engagement (<code>app_logins_frequency</code>, <code>weekend_transaction_ratio</code>, <code>recency</code>, <code>frequency</code>):</strong> How customers interact with the platform is a massive signal. The frequency of app logins and the recency of their last action are classic indicators of engagement. Furthermore, behavioral patterns, such as the proportion of transactions happening on weekends, provide strong signals to the model about a user’s routine and potential drop-off.</p></li>
<li><p><strong>Customer Sentiment &amp; Loyalty (<code>nps_score</code>, <code>customer_lifetime_value</code>, <code>tenure</code>):</strong> Direct customer feedback (<code>nps_score</code>) is the third most important variable, confirming that stated satisfaction strongly correlates with actual churn behavior. Additionally, historical loyalty metrics (<code>tenure</code> and <code>customer_lifetime_value</code>) are heavily weighed by the model to assess risk.</p></li>
<li><p><strong>Financial Indicators (<code>credit_utilization_ratio</code>):</strong> A customer’s financial footprint, specifically how much of their available credit they are utilizing, acts as a key variable. High or low utilization could be indicative of financial stress or shifting to a competitor’s product.</p></li>
</ul>
</div>
</div>
</section>
<section id="business-takeaway" class="level3">
<h3 class="anchored" data-anchor-id="business-takeaway">5.5 Business Takeaway</h3>
<p>The model relies most heavily on <code>age</code> and digital engagement (<code>app_logins_frequency</code>) rather than just financial metrics. To proactively prevent churn, retention strategies should be highly personalized by age group and focused on keeping users actively logging into the platform.</p>
</section>
</section>
<section id="ui-design" class="level2">
<h2 class="anchored" data-anchor-id="ui-design">6 UI Design</h2>
<section id="tab-1-macro-view-strategic-oversight" class="level3">
<h3 class="anchored" data-anchor-id="tab-1-macro-view-strategic-oversight">Tab 1: Macro View (Strategic Oversight)</h3>
<p><img src="images/clipboard-3056273627.png" class="img-fluid"></p>
<section id="description" class="level4">
<h4 class="anchored" data-anchor-id="description">Description</h4>
<p>The Macro View serves as a high-level command center for executives to optimize the financial trade-offs of the churn management strategy. It transitions the model from a technical output (probabilities) to a business output (dollars). By using a <strong>Churn Threshold Slider</strong>, users can simulate the impact of different risk tolerances on the company’s bottom line.</p>
</section>
<section id="data-visualization-design-principles" class="level4">
<h4 class="anchored" data-anchor-id="data-visualization-design-principles"><strong>Data Visualization &amp; Design Principles</strong></h4>
<ul>
<li><p><strong>Visual Hierarchy:</strong> Key Performance Indicators (KPIs) like <strong>Total Cost</strong> and <strong>Total CLV Retained</strong> are placed at the top to provide immediate situational awareness.</p></li>
<li><p><strong>The “Danger Zone” Histogram:</strong> This uses <strong>Distributional Analysis</strong> to show the density of risk. The vertical threshold line provides a clear visual cue of “Who we help” vs.&nbsp;“Who we ignore.”</p></li>
<li><p><strong>The Dynamic Confusion Matrix:</strong> This implements <strong>Real-time Feedback Loops</strong>. As the user moves the slider, the matrix shifts to show the immediate trade-off between “Wasted Spend” (False Positives) and “Lost Revenue” (False Negatives).</p></li>
<li><p><strong>The Dynamic Lift Chart:</strong> Focuses on <strong>Model Efficiency</strong>. It demonstrates the “Power” of the model by showing how much more effective the targeted intervention is compared to random guessing.</p></li>
</ul>
</section>
</section>
<section id="tab-2-micro-view-operational-simulation" class="level3">
<h3 class="anchored" data-anchor-id="tab-2-micro-view-operational-simulation">Tab 2: Micro View (Operational Simulation)</h3>
<p><img src="images/clipboard-1860893937.png" class="img-fluid"></p>
<section id="description-1" class="level4">
<h4 class="anchored" data-anchor-id="description-1"><strong>Description</strong></h4>
<p>The Micro View shifts the focus from “The Many” to “The One.” It is a diagnostic and prescriptive tool designed for account managers to understand individual customer distress and test potential solutions. It bridges the “Black Box” of Machine Learning by providing transparent, local explanations for every prediction.</p>
</section>
<section id="data-visualization-design-principles-1" class="level4">
<h4 class="anchored" data-anchor-id="data-visualization-design-principles-1"><strong>Data Visualization &amp; Design Principles</strong></h4>
<ul>
<li><p><strong>Contextual Filtering:</strong> The <strong>Search &amp; Selection</strong> interface allows users to drill down from a massive dataset to a single specific profile, maintaining <strong>Data Continuity</strong> across the workflow.</p></li>
<li><p><strong>SHAP Waterfall Chart:</strong> follows the principle of <strong>Transparency</strong>. It deconstructs a complex Random Forest prediction into a simple “Tug-of-War” visual, showing which specific behaviors (like NPS or App Logins) are driving that individual’s risk.</p></li>
<li><p><strong>Prescriptive “What-If” Simulation:</strong> This implements <strong>Active Learning</strong>. By providing “Actionable Levers” (sliders/toggles), the user can modify feature values (e.g., “What if we increase their credit limit?”) to see the <strong>Projected Risk</strong> update in real-time.</p></li>
<li><p><strong>Best Practices:</strong> The design limits the view to the <strong>Top 10 Strategic Variables</strong>, reducing <strong>Cognitive Load</strong> and ensuring the agent focuses only on factors the business can actually influence.</p></li>
</ul>


</section>
</section>
</section>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Xu Qianqian</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
      <i class="bi bi-heart-fill" role="img">
</i> 
 Made with Quarto
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>